version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mcpaystream-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mcpaystream
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mcpaystream-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mcpaystream-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/mcpaystream?authSource=admin
      SOLANA_RPC_URL: https://api.mainnet-beta.solana.com
      SOLANA_WS_URL: wss://api.mainnet-beta.solana.com
      COINGECKO_API_URL: https://api.coingecko.com/api/v3
      PORT: 5000
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mcpaystream-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mcpaystream-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000
      VITE_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - mcpaystream-network

volumes:
  mongodb_data:

networks:
  mcpaystream-network:
    driver: bridge
